export const APP = {
  name: 'Mesa a Dois',
  description:
    'Diário gastronômico de Gabriel e Milena: os lugares que visitamos, o que comemos e o que achamos.',
  footer: 'Feito com fome e carinho por Gabriel & Milena',
  mapCredits: 'Mapa ©',
} as const;

export const NAV = {
  map: 'Mapa',
  restaurants: 'Restaurantes',
  about: 'Sobre nós',
  login: 'Entrar',
  logout: 'Sair',
  newRestaurant: 'Novo restaurante',
  openMenu: 'Abrir menu',
  closeMenu: 'Fechar menu',
} as const;

export const HOME = {
  title: 'Onde já sentamos à mesa',
  subtitle: 'Clique em um item para ver o restaurante, nossas notas e o que pedimos.',
  stats: {
    restaurants: 'restaurantes',
    dishes: 'pratos provados',
    cities: 'cidades',
    average: 'nota média',
  },
  empty: 'Ainda não cadastramos nenhum restaurante. Em breve tem novidade por aqui!',
  seeDetails: 'Ver detalhes',
  seeAll: 'Ver todos em grade',
} as const;

export const RESTAURANTS = {
  title: 'Restaurantes',
  subtitle: 'Todos os lugares que já visitamos.',
  searchPlaceholder: 'Buscar por nome, cozinha, cidade ou prato…',
  sort: {
    label: 'Ordenar por',
    recent: 'Visita mais recente',
    rating: 'Melhor nota',
    name: 'Nome (A–Z)',
  },
  filters: {
    button: 'Filtros',
    clear: 'Limpar filtros',
    cuisine: 'Categoria',
    city: 'Cidade',
    price: 'Faixa de preço',
    rating: 'Nota mínima',
    ratingAny: 'Qualquer nota',
    ratingMin: (n: number) => `${n}+`,
    period: 'Período da visita',
    from: 'De',
    to: 'Até',
    wouldReturn: 'Voltaríamos?',
    all: 'Todos',
    yes: 'Sim',
    no: 'Não',
    none: 'Nenhuma opção cadastrada ainda.',
    results: (shown: number, total: number) =>
      shown === total ? `${total} restaurante${total === 1 ? '' : 's'}` : `${shown} de ${total} restaurantes`,
  },
  emptyFiltered: 'Nenhum restaurante com esses filtros.',
  empty: 'Nenhum restaurante encontrado.',
  emptyAdmin: 'Nenhum restaurante ainda. Que tal cadastrar o primeiro?',
  dishCount: (n: number) => (n === 1 ? '1 prato' : `${n} pratos`),
  visitedOn: (date: string) => `Visitado em ${date}`,
  notVisited: 'Data não informada',
  wouldReturn: 'Voltaríamos',
  wouldNotReturn: 'Não voltaríamos',
  view: 'Visualizar',
  edit: 'Editar',
  delete: 'Excluir',
  back: 'Voltar',
  ratingGabriel: 'Gabriel',
  ratingMilena: 'Milena',
  average: 'Média',
  review: 'Nossa opinião',
  noReview: 'Sem comentários ainda.',
  location: 'Localização',
  openInMaps: 'Abrir no Google Maps',
  priceLevel: 'Faixa de preço',
  confirmDeleteTitle: 'Excluir restaurante?',
  confirmDeleteText: (name: string) =>
    `“${name}” e todos os pratos cadastrados nele serão excluídos. Essa ação não pode ser desfeita.`,
  deleted: 'Restaurante excluído.',
  notFound: 'Restaurante não encontrado.',
} as const;

export const DISHES = {
  title: 'O que comemos',
  empty: 'Nenhum prato cadastrado.',
  add: 'Adicionar prato',
  edit: 'Editar prato',
  delete: 'Excluir prato',
  newTitle: 'Novo prato',
  editTitle: 'Editar prato',
  confirmDeleteTitle: 'Excluir prato?',
  confirmDeleteText: (name: string) => `“${name}” será removido. Essa ação não pode ser desfeita.`,
  saved: 'Prato salvo!',
  deleted: 'Prato excluído.',
} as const;

export const CUISINES = [
  'Açaí',
  'Árabe',
  'Bar & Petiscos',
  'Brasileira',
  'Cafeteria',
  'Churrascaria',
  'Confeitaria & Doces',
  'Contemporânea',
  'Francesa',
  'Frutos do Mar',
  'Gaúcha',
  'Hamburgueria',
  'Italiana',
  'Japonesa',
  'Lanches',
  'Mexicana',
  'Padaria',
  'Pizzaria',
  'Portuguesa',
  'Sorveteria',
  'Tailandesa',
  'Vegetariana & Vegana',
  'Outra',
] as const;

export const FORM = {
  newTitle: 'Novo restaurante',
  editTitle: 'Editar restaurante',
  sections: {
    basic: 'Informações básicas',
    location: 'Localização',
    ratings: 'Avaliação',
  },
  fields: {
    name: 'Nome',
    cuisine: 'Tipo de cozinha',
    cuisinePlaceholder: 'Selecione a categoria',
    description: 'Descrição curta',
    address: 'Endereço',
    city: 'Cidade',
    visitedAt: 'Data da visita',
    priceLevel: 'Faixa de preço',
    logo: 'Foto do restaurante',
    logoHint: 'Logo ou foto do lugar. Ocupa o card inteiro, o topo da página e aparece no pin do mapa.',
    ratingGabriel: 'Nota do Gabriel (0–10)',
    ratingMilena: 'Nota da Milena (0–10)',
    review: 'Nossa opinião',
    reviewPlaceholder: 'Como foi a experiência? Atendimento, ambiente, o que valeu a pena…',
    wouldReturn: 'Voltaríamos a esse lugar',
    latitude: 'Latitude',
    longitude: 'Longitude',
    dishName: 'Nome do prato',
    dishDescription: 'Descrição',
    dishPrice: 'Preço (R$)',
    dishPhoto: 'Foto do prato',
  },
  priceLevels: ['Não informado', '$ — Econômico', '$$ — Moderado', '$$$ — Caro', '$$$$ — Especial'],
  addressLabel: 'Endereço ou nome do lugar',
  addressPlaceholder: 'Comece a digitar: “Cantina da Nonna” ou “Rua Independência, 100”',
  addressHint: 'Escolha uma sugestão para preencher o endereço, a cidade e o pin automaticamente.',
  noSuggestions: 'Nenhuma sugestão. Digite mais detalhes ou marque direto no mapa.',
  geocodeError: 'Busca de endereços indisponível agora. Marque o local direto no mapa.',
  mapHint: 'Clique no mapa ou arraste o pin para ajustar a posição exata.',
  pinSet: 'Pin definido',
  cityLabel: (city: string) => `Cidade: ${city}`,
  cityResolving: 'Identificando a cidade…',
  cityEdit: 'corrigir',
  pinMissing: 'Local ainda não marcado no mapa.',
  useMyLocation: 'Usar minha localização',
  upload: 'Enviar imagem',
  uploading: 'Enviando…',
  removeImage: 'Remover imagem',
  save: 'Salvar',
  saving: 'Salvando…',
  cancel: 'Cancelar',
  saved: 'Restaurante salvo!',
  errors: {
    required: 'Campo obrigatório',
    rating: 'A nota deve ser entre 0 e 10 (passo de 0,5)',
    location: 'Defina a localização no mapa',
    price: 'Informe um valor válido',
    generic: 'Não foi possível salvar. Tente novamente.',
  },
} as const;

export const LOGIN = {
  title: 'Área do casal',
  subtitle: 'Entre para cadastrar, editar e excluir restaurantes e pratos.',
  email: 'E-mail',
  password: 'Senha',
  submit: 'Entrar',
  submitting: 'Entrando…',
  invalid: 'E-mail ou senha inválidos.',
  emailInvalid: 'Informe um e-mail válido',
  passwordRequired: 'Informe a senha',
  alreadyLogged: 'Você já está conectado.',
  mfaTitle: 'Verificação em duas etapas',
  mfaSubtitle: 'Digite o código de 6 dígitos do seu app autenticador.',
  mfaCode: 'Código',
  mfaInvalid: 'Código inválido ou expirado.',
  mfaBack: 'Voltar',
  locked: 'Muitas tentativas. Aguarde alguns minutos e tente novamente.',
  mfaSetupTitle: 'Ative a verificação em duas etapas',
  mfaSetupText:
    'Por segurança, o acesso exige um código do app autenticador. Peça ao administrador para ativar o 2FA da sua conta pelo terminal:',
  mfaSetupCommand: (email: string) => `npm run user -- 2fa:enable ${email}`,
  backHome: 'Voltar para o mapa',
} as const;

export const ABOUT = {
  title: 'Sobre nós',
  intro:
    'Somos Gabriel e Milena, um casal que descobriu que as melhores conversas acontecem em volta de uma mesa. O Mesa a Dois nasceu para guardar essas memórias: cada restaurante, cada prato e a nota sincera que demos a eles.',
  people: [
    {
      name: 'Gabriel',
      photo: '/about/gabriel.webp',
      role: 'Desenvolvedor & provador oficial de sobremesas',
      bio: 'Desenvolvedor, curioso por natureza. Construiu este site e não recusa um bom hambúrguer artesanal — nem uma segunda sobremesa.',
    },
    {
      name: 'Milena',
      photo: '/about/milena.webp',
      role: 'Psicóloga & crítica exigente',
      bio: 'Repara em cada detalhe: do atendimento ao empratamento. É quem escolhe os lugares novos e quem dá a palavra final sobre voltar ou não.',
    },
  ],
  howTitle: 'Como avaliamos',
  how: [
    { title: 'Notas separadas', text: 'Cada um dá sua nota de 0 a 10. A média aparece em destaque.' },
    { title: 'O que comemos', text: 'Registramos os pratos com foto, preço e nota individual.' },
    { title: 'Voltaríamos?', text: 'A pergunta que resume tudo: vale a pena voltar?' },
  ],
  ctaTitle: 'Explore nosso mapa',
  ctaButton: 'Ver o mapa',
} as const;

export const COMMON = {
  loading: 'Carregando…',
  error: 'Algo deu errado. Tente novamente.',
  retry: 'Tentar novamente',
  confirm: 'Confirmar',
  cancel: 'Cancelar',
  close: 'Fechar',
  notFoundTitle: 'Página não encontrada',
  notFoundText: 'Parece que essa mesa não está reservada.',
} as const;
